name: Run a notebook in databricks on PRs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   environment:
    name: 'Development'
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: databricks-import-directory
       uses: microsoft/databricks-import-notebook@v1.0.0
       with:
          databricks-host: https://adb-3469227931728291.11.azuredatabricks.net
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          local-path: ./DataFiles/SampleFile2.csv
          remote-path: /dbfs/FileStore/tables/CBDataFiles/SampleFile2.csv
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: ./workbooks/1-first.py
         databricks-host: https://adb-3469227931728291.11.azuredatabricks.net
         databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
         git-commit: ${{ github.event.pull_request.head.sha }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "10.4.x-scala2.12",
             "node_type_id": "Standard_D3_v2"
           }
